trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap
      host: localhost
      port: 8080
      user: "{{ env_var('TRINO_USER') }}"
      password: "{{ env_var('TRINO_PASSWORD') }}"
      database: main_warehouse
      schema: dev
      threads: 4
